[build]
  command = "NITRO_PRESET=netlify bun run build"
  publish = "dist"

[build.environment]
  NITRO_PRESET = "netlify"

[functions]
  directory = ".netlify/functions-internal"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200
